FROM opentosca/winery:v3.0.0-M1
LABEL maintainer = "Benjamin Weder <weder@iaas.uni-stuttgart.de>"

ENV WINERY_REPOSITORY_PATH /var/repository/modulo

COPY --chown=winery ./tosca-definitions /var/repository/modulo