FROM beiselmn/winery:3.0.3
LABEL maintainer = "Benjamin Weder <weder@iaas.uni-stuttgart.de>"

ENV WINERY_REPOSITORY_PATH /var/repository/modulo

COPY --chown=winery ./tosca-definitions /var/repository/modulo
