version: '3'

services:
  #############
  # Databases #
  #############

  db:
    build:
      context: ./db
    image: quantil-db
    environment:
      # specifies user:password for each container
      POSTGRES_USERS: 'planqk:planqk|patternatlas:patternatlas|qprov:qprov|registry:registry'
      # specifies database:user for each container
      POSTGRES_DATABASES: 'planqk:planqk|patternatlas:patternatlas|qprov:qprov|registry:registry'
      QC_ATLAS_CONTENT_REPOSITORY_BRANCH: 'master'
      ATLAS_DB: planqk
      NISQ_DB: nisq
      PATTERNATLAS_DB: patternatlas
      QPROV_DB: qprov
    ports:
      - '5060:5060'
    networks:
      - planqk-demo
  
  redis:
    image: redis:6.2.2
    ports:
      - "5040:5040"
    command: --port 5040
    networks:
      - planqk-demo
  
  ############
  # QC Atlas #
  ############

  qc-atlas-ui:
    image: planqk/qc-atlas-ui:latest
    depends_on:
      - config-server
    environment:
      # because the requests are performed from the browser and not
      # from the container itself we have to specify localhost here
      # and **not** the container name
      QC_ATLAS_HOST_NAME: localhost
      QC_ATLAS_PORT: 6626
      PATTERN_ATLAS_HOST_NAME: localhost
      PATTERN_ATLAS_PORT: 1977
      PATTERN_ATLAS_UI_HOST_NAME: localhost
      PATTERN_ATLAS_UI_PORT: 1978
      NISQ_ANALYZER_HOST_NAME: localhost
      NISQ_ANALYZER_PORT: 5010
      QPROV_HOST_NAME: localhost
      QPROV_PORT: 5020
      LATEX_RENDERER_HOST_NAME: localhost
      LATEX_RENDERER_PORT: 5030
    ports:
      - '8060:80'
    volumes:
      - ./config:/opt/init-config.d
    networks:
      - planqk-demo
  qc-atlas:
    image: planqk/atlas:latest
    depends_on:
      - db
    environment:
      POSTGRES_HOSTNAME: db
      POSTGRES_PORT: 5060
      POSTGRES_USER: planqk
      POSTGRES_PASSWORD: planqk
      POSTGRES_DB: planqk
    ports:
      - "6626:6626"
    networks:
      - planqk-demo

  ####################
  # Workflow Modeler #
  ####################

  workflow-modeler:
    image: planqk/workflow-modeler:local
    platform: linux/amd64
    environment:
     CAMUNDA_ENDPOINT: http://$PUBLIC_HOSTNAME:8090/engine-rest
     PATTERN_ATLAS_ENDPOINT: http://$PUBLIC_HOSTNAME:1977/patternatlas/patternLanguages/af7780d5-1f97-4536-8da7-4194b093ab1d
     OPENTOSCA_ENDPOINT: http://$PUBLIC_HOSTNAME:1337/csars
     WINERY_ENDPOINT: http://$PUBLIC_HOSTNAME:8093/winery
     ENABLE_DATA_FLOW_PLUGIN: 'false'
     ENABLE_PLANQK_PLUGIN: 'false'
     ENABLE_QHANA_PLUGIN: 'false'
     ENABLE_QUANTME_PLUGIN: 'true'
     QRM_USERNAME: 'LaviniaStiliadou'
     QRM_REPONAME: 'QuantME-UseCases'
     QRM_REPOPATH: '2023-icwe/qrms'
    ports:
      - 8061:8080
    networks:
      - planqk-demo
  
  transformation-backend:
    image: planqk/quantme-backend:v1.8.0
    platform: linux/amd64
    environment:
      CAMUNDA_ENDPOINT: http://${PUBLIC_HOSTNAME}:8090/engine-rest
      OPENTOSCA_ENDPOINT: http://${PUBLIC_HOSTNAME}:1337/csars
      PORT: 8888
      QRM_USERNAME: ${QRM_USERNAME}
      QRM_REPONAME: ${QRM_REPONAME}
      QRM_REPOPATH: ${QRM_REPOPATH}
      WINERY_ENDPOINT: http://${PUBLIC_HOSTNAME}:8093/winery
    ports:
      - 8888:8888
    networks:
      - planqk-demo

  camunda-engine:
    image: camunda/camunda-bpm-platform:run-7.19.0
    ports:
      - 8090:8080
    networks:
      - planqk-demo

  #################
  # Pattern Atlas #
  #################

  pattern-atlas-api:
    image: patternatlas/pattern-atlas-api:latest
    environment:
      JDBC_DATABASE_URL: db
      JDBC_DATABASE_USERNAME: patternatlas
      JDBC_DATABASE_PASSWORD: patternatlas
      JDBC_DATABASE_PORT: 5060
      DB_INIT_USER: patternatlas
      DB_INIT_PASSWORD: patternatlas
      LATEX_RENDERER_HOST_NAME: latex-renderer
      LATEX_RENDERER_PORT: 5030
      JDBC_DATABASE_NAME: patternatlas
      PATTERN_ATLAS_FETCH_INITIAL_DATA: 'true'
      HAL_EXPLORER: 'false'
      #PATTERN_ATLAS_CONTENT_REPOSITORY_BRANCH: feature/known_uses
      # activate correct application properties
      SPRING_PROFILES_ACTIVE: docker
      JWK_URI: http://auth:8080/realms/patternatlas/protocol/openid-connect/certs
      SECURITY_LOGLEVEL: info
    ports:
      - "1977:1977"
    networks:
      - planqk-demo
    depends_on:
      - db
      - latex-renderer
    restart: on-failure

  pattern-atlas-ui:
    image: patternatlas/pattern-atlas-ui:v1.5.6
    platform: linux/x86_64
    depends_on:
      - config-server
    environment:
      # because the requests are performed from the browser and not
      # from the container itself we have to specify localhost here
      # and **not** the container name
      PATTERN_ATLAS_API_HOST_NAME: localhost
      PATTERN_ATLAS_API_PORT: 1977
      LATEX_RENDERER_HOST_NAME: localhost
      LATEX_RENDERER_PORT: 5030
      URL_SCHEME: http
      AUTH_REALM_URL: http://localhost:7080/realms/patternatlas
    ports:
      - "1978:80"
    networks:
      - planqk-demo

  auth:
    image: quay.io/keycloak/keycloak:18.0.0
    command: start-dev --import-realm
    volumes:
      - ./keycloak_import:/opt/keycloak/data/import
    environment:
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_ADMIN: admin
    ports:
      - "7080:8080"
    networks:
      - planqk-demo

  config-server:
    image: quay.io/coreos/etcd:latest
    platform: linux/amd64
    environment:
      ETCD_NAME: config-node1
      ETCD_CORS: "*"
      ETCD_ADVERTISE_CLIENT_URLS: "http://config-server:2379"
      ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2379"
      ETCDCTL_API: 3
    ports:
      - "2379:2379"
    networks:
      - planqk-demo

  # used by the pattern atlas to render latex
  latex-renderer:
    image: planqk/latex-renderer:v1.1.1
    platform: linux/amd64
    ports:
      - "5030:5030"
    networks:
      - planqk-demo

  qiskit-service:
    image: planqk/qiskit-service:latest
    command: sh /app/startup.sh
    ports:
      - "5013:5013"
    environment:
      - REDIS_URL=redis://redis:5040
      - DATABASE_URL=sqlite:////data/app.db
    volumes:
      - exec_data:/data
    networks:
      - planqk-demo

  qiskit-rq-worker:
    image: planqk/qiskit-service:latest
    command: rq worker --url redis://redis:5040 qiskit-service_execute
    environment:
      - REDIS_URL=redis://redis:5040
      - DATABASE_URL=sqlite:////data/app.db
    volumes:
      - exec_data:/data
    depends_on:
      - redis
    deploy:
      replicas: 1
    networks:
      - planqk-demo
  
##########
# Quokka #
##########

  execution-service:
    image: stiliala/execution-service:latest
    platform: linux/amd64
    ports:
      - '5075:5075'
    networks:
      - planqk-demo
      
  optimization-service:
    image: planqk/optimization-service:v0.3.0
    platform: linux/amd64
    ports:
      - '5074:5074'
    environment:
      CAMUNDA_ENDPOINT: http://$PUBLIC_HOSTNAME:8090/engine-rest
    networks:
      - planqk-demo
    env_file:
      - .env
      
  objective-evaluation-service:
    image: planqk/objective-evaluation-service:v0.2.0
    platform: linux/amd64
    ports:
      - '5072:5072'
    networks:
      - planqk-demo
      
  circuit-generation-service:
    image: planqk/quantum-circuit-generator:v0.2.0
    platform: linux/amd64
    ports:
      - '5073:5073'
    networks:
      - planqk-demo

  circuit-cutting-service:
    image: planqk/circuit-cutting-service:v0.1.0
    platform: linux/amd64
    ports:
      - '5076:5076'
    networks:
      - planqk-demo

  warm-starting-service:
    image: planqk/warm-starting-service:v0.1.0
    platform: linux/amd64
    ports:
      - '5077:5077'
    networks:
      - planqk-demo

  quokka-gateway:
    image: planqk/quokka-gateway:0.2.0
    ports:
      - '6474:6474'
    networks:
      - planqk-demo

networks:
  planqk-demo:
    driver: bridge
volumes:
  exec_data:
  instance:
  minio:
  experiments: