version: '3.6'
services:      
  db:
    image: postgres:15
    environment:
        POSTGRES_USER: patternatlas
        POSTGRES_PASSWORD: patternatlas
        POSTGRES_DB: patternatlas
    ports:
        - "5060:5432"
    networks:
      - default
  pattern-atlas-api:
    image: patternatlas/pattern-atlas-api:latest
    environment:
      JDBC_DATABASE_URL: db
      JDBC_DATABASE_USERNAME: patternatlas
      JDBC_DATABASE_PASSWORD: patternatlas
      JDBC_DATABASE_PORT: 5432
      DB_INIT_USER: patternatlas
      DB_INIT_PASSWORD: patternatlas
      LATEX_RENDERER_HOST_NAME: latex-renderer
      LATEX_RENDERER_PORT: 5030
      JDBC_DATABASE_NAME: patternatlas
      PATTERN_ATLAS_FETCH_INITIAL_DATA: 'true'
      HAL_EXPLORER: 'false'
      #PATTERN_ATLAS_CONTENT_REPOSITORY_BRANCH: feature/known_uses
      # activate correct application properties
      SPRING_PROFILES_ACTIVE: docker
      JWK_URI: http://auth:8080/realms/patternatlas/protocol/openid-connect/certs
      SECURITY_LOGLEVEL: info
    ports:
      - "1977:1977"
    networks:
      - default
    depends_on:
      - db
      - latex-renderer
    restart: on-failure
  latex-renderer:
    image: planqk/latex-renderer:v1.1.1
    ports:
      - "5030:5030"
networks:
  default:
    driver: bridge
