version: '4'

services:
  #############
  # Databases #
  #############

  db:
    build:
      context: ./db
    image: quantil-db
    environment:
      # specifies user:password for each container
      POSTGRES_USERS: 'planqk:planqk|patternatlas:patternatlas|qprov:qprov|registry:registry'
      # specifies database:user for each container
      POSTGRES_DATABASES: 'planqk:planqk|patternatlas:patternatlas|qprov:qprov|registry:registry'
      QC_ATLAS_CONTENT_REPOSITORY_BRANCH: 'master'
      ATLAS_DB: planqk
      PATTERNATLAS_DB: patternatlas
      QPROV_DB: qprov
    ports:
      - '5060:5060'
    networks:
      - planqk-demo
  
  
  ############
  # QC Atlas #
  ############

  # connection between the pattern and solutions
  qc-atlas:
    image: planqk/atlas:latest
    depends_on:
      - db
    environment:
      POSTGRES_HOSTNAME: db
      POSTGRES_PORT: 5060
      POSTGRES_USER: planqk
      POSTGRES_PASSWORD: planqk
      POSTGRES_DB: planqk
    ports:
      - "6626:6626"
    networks:
      - planqk-demo

  #############################
  # Workflow Modeler + Engine #
  #############################

  workflow-modeler:
    image: planqk/workflow-modeler:v1.2.0
    environment:
     CAMUNDA_ENDPOINT: http://$PUBLIC_HOSTNAME:8090/engine-rest
     PATTERN_ATLAS_ENDPOINT: http://$PUBLIC_HOSTNAME:1977/patternatlas/patternLanguages/af7780d5-1f97-4536-8da7-4194b093ab1d
     OPENTOSCA_ENDPOINT: http://$PUBLIC_HOSTNAME:1337/csars
     WINERY_ENDPOINT: http://$PUBLIC_HOSTNAME:8093/winery
     ENABLE_DATA_FLOW_PLUGIN: 'false'
     ENABLE_PATTERN_PLUGIN: 'true'
     ENABLE_PLANQK_PLUGIN: 'false'
     ENABLE_QHANA_PLUGIN: 'false'
     ENABLE_QUANTME_PLUGIN: 'true'
     QRM_USERNAME: 'LaviniaStiliadou'
     QRM_REPONAME: 'QuantME-UseCases'
     QRM_REPOPATH: '2023-icwe/qrms'
    ports:
      - 8080:8080
    networks:
      - planqk-demo

  camunda-engine:
    image: planqk/camunda-process-views-plugin:v1.0.0
    ports:
      - 8090:8080
    networks:
      - planqk-demo

  #################
  # Pattern Atlas #
  #################

  # allows to retrieve information of each pattern
  pattern-atlas-api:
    image: patternatlas/pattern-atlas-api:latest
    environment:
      JDBC_DATABASE_URL: db
      JDBC_DATABASE_USERNAME: patternatlas
      JDBC_DATABASE_PASSWORD: patternatlas
      JDBC_DATABASE_PORT: 5060
      DB_INIT_USER: patternatlas
      DB_INIT_PASSWORD: patternatlas
      LATEX_RENDERER_HOST_NAME: latex-renderer
      LATEX_RENDERER_PORT: 5030
      JDBC_DATABASE_NAME: patternatlas
      PATTERN_ATLAS_FETCH_INITIAL_DATA: 'true'
      HAL_EXPLORER: 'false'
      # activate correct application properties
      SPRING_PROFILES_ACTIVE: docker
      SECURITY_LOGLEVEL: info
    ports:
      - "1977:1977"
    networks:
      - planqk-demo
    depends_on:
      - db
      - latex-renderer

  # contains more information regarding the patterns
  pattern-atlas-ui:
    image: patternatlas/pattern-atlas-ui:v1.5.6
    platform: linux/x86_64
    environment:
      # because the requests are performed from the browser and not
      # from the container itself we have to specify localhost here
      # and **not** the container name
      PATTERN_ATLAS_API_HOST_NAME: localhost
      PATTERN_ATLAS_API_PORT: 1977
      LATEX_RENDERER_HOST_NAME: localhost
      LATEX_RENDERER_PORT: 5030
      URL_SCHEME: http
    ports:
      - "1978:80"
    networks:
      - planqk-demo

  # required by the pattern atlas to render latex
  latex-renderer:
    image: planqk/latex-renderer:v1.1.1
    platform: linux/amd64
    ports:
      - "5030:5030"
    networks:
      - planqk-demo
  
##########
# Quokka #
##########

  execution-service:
    image: stiliala/execution-service:latest
    platform: linux/amd64
    ports:
      - '5075:5075'
    networks:
      - planqk-demo
      
  optimization-service:
    image: planqk/optimization-service:v0.3.0
    platform: linux/amd64
    ports:
      - '5074:5074'
    environment:
      CAMUNDA_ENDPOINT: http://$PUBLIC_HOSTNAME:8090/engine-rest
    networks:
      - planqk-demo
    env_file:
      - .env
      
  objective-evaluation-service:
    image: planqk/objective-evaluation-service:v0.2.0
    platform: linux/amd64
    ports:
      - '5072:5072'
    networks:
      - planqk-demo
      
  circuit-generation-service:
    image: planqk/quantum-circuit-generator:v0.2.0
    platform: linux/amd64
    ports:
      - '5073:5073'
    networks:
      - planqk-demo

  warm-starting-service:
    image: planqk/warm-starting-service:v0.1.0
    platform: linux/amd64
    ports:
      - '5077:5077'
    networks:
      - planqk-demo

  quokka-gateway:
    image: planqk/quokka-gateway:0.2.0
    ports:
      - '6474:6474'
    networks:
      - planqk-demo

networks:
  planqk-demo:
    driver: bridge
volumes:
  exec_data:
  instance:
  minio:
  experiments:
