services:
  ### Quokka ecosystem ###
      
      
  execution-service:
    image: planqk/execution-service:latest
    #build: ./services/execution-service
    ports:
      - '5075:5075'
    networks:
      - icwe-demo
      
  optimization-service:
    image: planqk/optimization-service:latest
    #build: ./services/optimization-service
    ports:
      - '5074:5074'
    networks:
      - icwe-demo
    env_file:
     - .env
      
  objective-evaluation-service:
    image: planqk/objective-evaluation-service:latest
    ports:
      - '5072:5072'
    networks:
      - icwe-demo
      
  circuit-generation-service:
    image: planqk/quantum-circuit-generator:latest
    ports:
      - '5073:5073'
    networks:
      - icwe-demo

  circuit-cutting-service:
    image: planqk/circuit-cutting-service:v0.1.0
    ports:
      - '5076:5076'
    networks:
      - icwe-demo

  warm-starting-service:
    image: planqk/warm-starting-service:latest
    ports:
      - '5077:5077'
    networks:
      - icwe-demo

  quokka-gateway:
    image: planqk/quokka-gateway:0.2.0
    ports:
      - '6474:6474'
    networks:
      - icwe-demo

  #######################
  ### qiskit service ####
  redis:
    image: redis:latest
    command: --port 5040
    ports:
      - "5040:5040"
    networks:
      - icwe-demo

  qiskit-service:
    image: planqk/qiskit-service:latest
    command: sh /app/startup.sh
    ports:
      - "5013:5013"
    environment:
      - REDIS_URL=redis://redis:5040
      - DATABASE_URL=sqlite:////data/app.db
    volumes:
      - exec_data:/data
    networks:
      - icwe-demo

  qiskit-rq-worker:
    image: planqk/qiskit-service:latest
    command: rq worker --url redis://redis:5040 qiskit-service_execute
    environment:
      - REDIS_URL=redis://redis:5040
      - DATABASE_URL=sqlite:////data/app.db
    volumes:
      - exec_data:/data
    depends_on:
      - redis
    deploy:
      replicas: 2
    networks:
      - icwe-demo

  rq-dashboard:
    image: eoranged/rq-dashboard
    ports:
      - "9181:9181"
    environment:
      - RQ_DASHBOARD_REDIS_URL=redis://redis:5040
    networks:
      - icwe-demo
  # end of qiskit service
  ########
