FROM opentosca/winery:latest
LABEL maintainer = "Benjamin Weder <weder@iaas.uni-stuttgart.de>"

ENV WINERY_REPOSITORY_PATH /var/repository/hardware-selection

COPY --chown=winery ./tosca-definitions /var/repository/hardware-selection